include:
  - .environment/database/docker-compose.yml
  - .environment/observability/docker-compose.yml
  - .environment/gateway/docker-compose.yml
  - .environment/test/docker-compose.yml
services:
  entry-api:
    build: ./apps/entry-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=pg_entry_primary;Port=5432;Database=postgres;Username=postgres;Password=password"
    depends_on:
      - pg_entry_primary
  consolidation-api:
    build: ./apps/consolidation-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=pg_consolidate;Port=5432;Database=postgres;Username=postgres;Password=password"
      ConnectionStrings__DefaultConnection2: "Host=pg_entry_replica;Port=5432;Database=postgres;Username=postgres;Password=password"
    ports:
      - "5002:8080"
    depends_on:
      - pg_entry_primary
      - pg_consolidate
  web-app:
    build:
      context: ./apps/web-app
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 50M
    ports:
      - "3000:80"